"""phase20 add actor column

Revision ID: 1264da85e19c
Revises: 40757e97742d
Create Date: 2026-09-09 23:30:24.575833

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1264da85e19c'
down_revision: Union[str, Sequence[str], None] = '40757e97742d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_tasks', schema=None) as batch_op:
        batch_op.drop_column('actor')

    # ### end Alembic commands ###
